sudo: false
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
  yarn: true
script:
  - yarn build
before_deploy:
  - export TRAVIS_COMMIT_MESSAGE="[deploy] $(git log --format='%h - %B' --no-merges -n 1)"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  email: $GITHUB_EMAIL
  name: SealUI-bot
  committer_from_gh: false
  allow_empty_commit: true
  on:
    branch: master
branches:
  only:
    - master
